# Configuration file for mapping of Thetered-TRIP experiments performed in K562 cells.
# This configuration contains all configurations used by the pipeline.
# Different parts of the pipeline use this configuration:
#
# snakemake:
#   this part mainly contains input files and a description of each file
#   the following input files are used:
#     - cDNA:
#         fastq files with cDNA reads of barcoded reporters
#     - gDNA:
#         fastq files with gDNA reads of barcoded reporters used to normalize the cDNA (cDNA) reads
#     - spike-in:
#         fastq file with only reads of the spike-in library which was mixed in with the cDNA and gDNA reads.
#     - forward_mapping:
#         fastq files with forward iPCR reads of reporter integrations containing barcodes.
#     - reverse_mapping:
#         fastq files with reverse iPCR reads of reporter integrations with intergration site.

###############################
### snakemake configuration ###
###############################
outdir: 'cl20170913_TRIP_K562_evsr'


input_file:
  gDNA:
    6A_rep1:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_6A_rep1.fq.gz
      - 10
    6A_rep2:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_6A_rep2_gDNA.fq.gz
      - 10
    6B_rep1:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_6B_rep1.fq.gz
      - 10
    6B_rep2:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_6B_rep2_gDNA.fq.gz
      - 10
    8A_rep1:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_8A_rep1.fq.gz
      - 10
    8A_rep2:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_8A_rep2_gDNA.fq.gz
      - 10
    8B_rep1:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_8B_rep1.fq.gz
      - 10
    8B_rep2:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_8B_rep2_gDNA.fq.gz
      - 10
    11A_rep1:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_11A_rep1.fq.gz
      - 10
    11A_rep2:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_11A_rep2_gDNA.fq.gz
      - 10
    11B_rep1:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_11B_rep1.fq.gz
      - 10
    11B_rep2:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_11B_rep2_gDNA.fq.gz
      - 10
  cDNA:
    6A_rep1:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_6A_rep1_cDNA.fq.gz
      - 10
    6A_rep2:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_6A_rep2_cDNA.fq.gz
      - 10
    6B_rep1:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_6B_rep1_cDNA.fq.gz
      - 10
    6B_rep2:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_6B_rep2_cDNA.fq.gz
      - 10
    8A_rep1:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_8A_rep1_cDNA.fq.gz
      - 10
    8A_rep2:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_8A_rep2_cDNA.fq.gz
      - 10
    8B_rep1:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_8B_rep1_cDNA.fq.gz
      - 10
    8B_rep2:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_8B_rep2_cDNA.fq.gz
      - 10
    11A_rep1:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_11A_rep1_cDNA.fq.gz
      - 10
    11A_rep2:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_11A_rep2_cDNA.fq.gz
      - 10
    11B_rep1:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_11B_rep1_cDNA.fq.gz
      - 10
    11B_rep2:
      - /home/c.leemans/mydata/projects/trip/cl20170913_TRIP_K562_evsr/raw_data/4596_1_BarcodedPool_NoIndex_Pool_11B_rep2_cDNA.fq.gz
      - 10


###############################################################################
###++++++++++++++++++++++++++++ parser settings ++++++++++++++++++++++++++++###
###############################################################################
# Typical structure of gDNA and cDNA reads:
#      index            pat1               barcode           pat2
# NNNNNNNNNNGTCACAAGGGCCGGCCACAACTCGAGNNNNNNNNNNNNNNNNTGATCCTGCAGTGTCACC...
#
# settings:
#   barcode_length -- the length of the barcode
#   pat1 -- the first constant pattern (after index, before barcode)
#   pat2 -- the pattern after the barcode
# #****************************************************************************
# Typical structures of mapping reads
#
# Forward Read:
#
# format_map1
#      index   	        pat1             barcode     pat2		genomic DNA
# NNNNNNNNNNGTCACAAGGGCCGGCCACAACTCGAGNNNNNNNNNNNNNNNNTGATCNNNNNNNNNNNNNNNNNNNN
#
# Reverse Read:
# 	     map_pat_rev					     genomic DNA
# GTACGTCACAATATGATTATCTTTCTAGGGTTAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

structure:
  mapping: |
    ID      5'      3'      type    req     second-read     pos   keep-bases
    index   %i      -       const   present False   fixed   -
    map_pat1a       GTCACAAGGGCCGGCCACAAC   -       const   present False   fixed   -
    const_bar       TCGAG\{16\}TGATC  -       const_bar       present False   fixed   -
    rev_map_complement      -       TTAACCCTAGAAAGATAATCATATTGTGACGTAC      const   -       False   var   -
    rev_map GTACGTCACAATATGATTATCTTTCTAGGGTTAA      -       const   present True    fixed   -
    fwd_map_complement      -       GATCA[BC]CTCGAGTTGTGGCCGGCCCTTGTGAC     const_bar_comp  -       True    var   -

  gDNA: |
    ID      5'      3'      type    req     second-read     pos                   keep-bases
    index   %i      -       const   present False   fixed                            -
    pat1    GTCACAAGGGCCGGCCACAACTCGAG      -       const   present False   fixed   -
    barcode 16      -       barcode present False   fixed   -
    pat2    TGATCCTGCAGTG   -       const   present False   var   -

  cDNA: |
    ID      5'      3'      type    req     second-read     pos     keep-bases
    index   %i      -       const   present False   fixed   -
    pat1    GTCACAAGGGCCGGCCACAACTCGAG      -       const   present False   fixed   -
    barcode 16      -       barcode present False   fixed   -
    pat2    TGATCCTGCAGTG   -       const   present False   var   -

  spike: |
    ID      5'      3'      type    req     second-read     pos     keep-bases
    index   %i      -       const   present False   fixed   -
    pat1    GTCACAAGGGCCGGCCACAA    -       const   present False   fixed   -
    barcode 16      -       barcode present False   fixed   -
    pat2    GATCGGTACCCA    -       const   present False   var   -

lev_dist: 2

min_count:
  spike: 1000
  gDNA: 5
  cDNA: 0
  map: 3

bowtie:
  index: /home/NFS/users/j.yanez/data/genomes/bowtie2/hg19
  options:
      '1': ['--very-sensitive']
      '2': ['--very-sensitive-local']


max_dist_for: 500

max_dist_rev: 20
