outdir: '/DATA/usr/c.leemans/projects/trip/cl20180704_TRIP_mixpool'

indir:
    /DATA/usr/c.leemans/data/forge/yx4x9aCqK2TJCuwR8UgDsLwcMORpOIiZ62uONIgQ

input_file:
    options:
        run856: [run856/5014_1_BarcodedPool_NoIndex_S11_R1_001.fastq.gz]
    pick:
        cDNA:
            cellmix:
                A: [run856, run856]
                B: [run856, run856]
            plasmid:
                A: [run856, run856]
                B: [run856, run856]
        gDNA:
            hPGK:
                A: [run856, run856]
            cellmix:
                A: [run856, run856]
                B: [run856, run856]
            plasmid:
                A: [run856, run856]
                B: [run856, run856]

index:
    cDNA:
        cellmix:
            A: [ATAGAGTACT, CACGCTACGT]
            B: [CAGTAGACGT, CGACGTGACT]
        plasmid:
            A: [TACACACACT, TACAGATCGT]
            B: [TACACGTGAT, TACGCTGTCT]
    gDNA:
        hPGK:
            A: [TCGTCGCTCG, ACATACGCGT]
        cellmix:
            A: [ACTGTACAGT, AGACTATACT]
            B: [ACGAGTGCGT, AGTACGCTAT]
        plasmid:
            A: [ACGCGAGTAT, ACGCGAGTAT]
            B: [ACTACTATGT, ACTACTATGT]

demultiplexed_indir: /DATA/usr/c.leemans/data/forge/yx4x9aCqK2TJCuwR8UgDsLwcMORpOIiZ62uONIgQ

demultiplexed_input:
    gDNA:
        '6':
            A:
                - M440/4945_1_BarcodedPool_NoIndex_pDNA_6A_r1.fq.gz
                - M440/4945_1_BarcodedPool_NoIndex_pDNA_6B_r2.fq.gz
        '8':
            A:
                - M440/4945_1_BarcodedPool_NoIndex_pDNA_8A_r1.fq.gz
                - M440/4945_1_BarcodedPool_NoIndex_pDNA_8B_r2.fq.gz
        '9':
            A:
                - M440/4945_1_BarcodedPool_NoIndex_pDNA_9A_r1.fq.gz
                - M440/4945_1_BarcodedPool_NoIndex_pDNA_9B_r2.fq.gz
        '10':
            A:
                - M440/4945_1_BarcodedPool_NoIndex_pDNA_10A_r1.fq.gz
                - M440/4945_1_BarcodedPool_NoIndex_pDNA_10B_r2.fq.gz
        '11':
            A:
                - M440/4945_1_BarcodedPool_NoIndex_pDNA_11A_r1.fq.gz
                - M440/4945_1_BarcodedPool_NoIndex_pDNA_11B_r2.fq.gz
        '12':
            A:
                - M440/4945_1_BarcodedPool_NoIndex_pDNA_12A_r1.fq.gz
                - M440/4945_1_BarcodedPool_NoIndex_pDNA_12B_r2.fq.gz

lev_dist: 2

min_count:
    gDNA: 5



starcode_params:
    options:
        gDNA:
            lev_dist: 2
            use_other: False
            other: gDNA
            count: 5
        cDNA:
            lev_dist: 2
            use_other: True
            other: gDNA
            count: 0
    pick:
        cDNA:
            cellmix:
                A: [cDNA, cDNA]
                B: [cDNA, cDNA]
            plasmid:
                A: [cDNA, cDNA]
                B: [cDNA, cDNA]
        gDNA:
            hPGK:
                A: [gDNA, gDNA]
            '6':
                A: [gDNA, gDNA]
            '8':
                A: [gDNA, gDNA]
            '9':
                A: [gDNA, gDNA]
            '10':
                A: [gDNA, gDNA]
            '11':
                A: [gDNA, gDNA]
            '12':
                A: [gDNA, gDNA]
            cellmix:
                A: [gDNA, gDNA]
                B: [gDNA, gDNA]
            plasmid:
                A: [gDNA, gDNA]
                B: [gDNA, gDNA]

structure:
    options:
        index: |
            ID      5'      3'      type    req     second-read     pos   keep-bases
            index   %s      -       index   present False   fixed   -
        cgDNA1: |
            ID      5'      3'      type    req     second-read     pos                   keep-bases
            pat1    GTCACAAGGGCCGGCCACAACTCGAG      -       const   present False   fixed   -
            barcode 16      -       barcode present False   fixed   -
            pat2    TGATCCTGCAGTG   -       const   present False   var   -
        cgDNA2: |
            ID      5'      3'      type    req     second-read     pos                   keep-bases
            index   10      -       const   present False           fixed                  -
            pat1    GTCACAAGGGCCGGCCACAACTCGAG      -       const   present False   fixed   -
            barcode 16      -       barcode present False   fixed   -
            pat2    TGATCCTGCAGTGTCACCTAAAT   -       const   present False   var   -
    pick:
        cDNA:
            cellmix: cgDNA1
            plasmid: cgDNA1
        gDNA:
            hPGK: cgDNA1
            '6': cgDNA2
            '8': cgDNA2
            '9': cgDNA2
            '10': cgDNA2
            '11': cgDNA2
            '12': cgDNA2
            cellmix: cgDNA1
            plasmid: cgDNA1
paired_end:
    cDNA: False
    gDNA: False



parser: ~t.v.schaik/mydata/modules/read-parsing/read_parser.py
