outdir: '/DATA/usr/c.leemans/projects/trip/cl20180823_TRIP_transient_mix'

indir:
    /DATA/usr/c.leemans/data/forge/yx4x9aCqK2TJCuwR8UgDsLwcMORpOIiZ62uONIgQ

input_file:
    options:
        M459: [M459/5073_1_BarcodedPool_NoIndex_S1_R1_001.fastq.gz]
    pick:
        cDNA:
            '1to1':
                A: [M459, M459]
                B: [M459, M459]
        gDNA:
            '1to1':
                A: [M459, M459]
                B: [M459, M459]

index:
    cDNA:
        '1to1':
            A: [TCTATACTAT, TGACGTATGT]
            B: [TGTGAGTAGT, ACAGTATATA]
    gDNA:
        '1to1':
            A: [TCGCACTAGT, TCGCACTAGT]
            B: [TCTAGCGACT, TCTAGCGACT]


lev_dist: 2

min_count:
    gDNA: 5



starcode_params:
    options:
        gDNA:
            lev_dist: 2
            use_other: False
            other: gDNA
            count: 5
        cDNA:
            lev_dist: 2
            use_other: True
            other: gDNA
            count: 0
    pick:
        cDNA:
            '1to1':
                A: [cDNA, cDNA]
                B: [cDNA, cDNA]
        gDNA:
            '1to1':
                A: [gDNA, gDNA]
                B: [gDNA, gDNA]

structure:
    options:
        index: |
            ID      5'      3'      type    req     second-read     pos   keep-bases
            index   %s      -       index   present False   fixed   -
        cgDNA: |
            ID      5'      3'      type    req     second-read     pos                   keep-bases
            pat1    GTCACAAGGGCCGGCCACAACTCGAG      -       const   present False   fixed   -
            barcode 16      -       barcode present False   fixed   -
            pat2    TGATCCTGCAGTGTCACCTAAAT   -       const   present False   var   -
    pick:
        cDNA:
            '1to1': cgDNA
        gDNA:
            '1to1': cgDNA
paired_end:
    cDNA: False
    gDNA: False



parser: ~t.v.schaik/mydata/modules/read-parsing/read_parser.py
